name: uniquote
description: UniQuote Mobile Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^1.0.3
  dio: ^2.1.3

  mobx: ^0.1.4
  flutter_mobx: ^0.1.3

  bottom_navy_bar: ^4.2.0


  #Official Plugins
  webview_flutter: ^0.3.7+1
  #flutterFire
  firebase_core: ^0.4.0
  firebase_analytics: ^3.0.1
  firebase_auth: ^0.11.0
  google_sign_in: ^4.0.1+3
  flare_flutter: ^1.5.0


  liquid_pull_to_refresh: ^1.1.0

  groovin_material_icons: ^1.1.6

  edge_alert: ^0.0.1
  share: ^0.6.1+1

  flutter_advanced_networkimage: ^0.4.15

  random_color: ^1.0.3

  validators: ^2.0.0+1

  gradient_widgets: ^0.4.1

  frideos_kvprx: ^0.2.0

  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.4.0
  mobx_codegen: ^0.1.3


flutter:


  uses-material-design: true

  assets:
    - assets/flare/
    - assets/img/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
