name: uniquote_flutter
description: UniQuote Mobile Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^2.1.6
  get_it: ^1.0.3+1
  mobx: ^0.2.0
  flutter_mobx: ^0.2.0+1

  timeago: ^2.0.16
  validators: ^2.0.0+1
  frideos_kvprx: ^0.3.0+1
  flutter_secure_storage: ^3.2.1+1

  #Official Plugins
  webview_flutter: ^0.3.7+1
  share: ^0.6.1+1
  #flutterFire
  firebase_core: ^0.4.0+1
  firebase_analytics: ^3.0.1
  firebase_auth: ^0.11.1+1
  google_sign_in: ^4.0.1+3
  flare_flutter: ^1.5.1

  groovin_material_icons: ^1.1.6
  flutter_advanced_networkimage: ^0.4.15
  image_picker: ^0.6.0+8
  datetime_picker_formfield: ^0.1.8

  liquid_pull_to_refresh: ^1.1.0
  bottom_navy_bar: ^4.2.0
  flutter_tags: ^0.3.1

  edge_alert: ^0.0.1
  achievement_view: ^0.1.2

  random_color: ^1.0.3
  gradient_widgets: ^0.4.1

  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.5.0
  mobx_codegen: ^0.2.0+1


flutter:

  uses-material-design: true

  assets:
    - assets/flare/
    - assets/img/
