name: uniquote
description: UniQuote Mobile Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.2
  get_it: ^1.0.3
  flutter_secure_storage: ^3.2.1+1
  dio: ^2.1.3

  mobx:
  flutter_mobx:
  expanding_bottom_bar: ^0.1.2

  bottom_navy_bar: ^4.0.0

  flare_flutter: ^1.5.0
  liquid_pull_to_refresh: ^1.1.0

  groovin_material_icons: ^1.1.6
  edge_alert: ^0.0.1
  share: ^0.6.1+1
  flutter_advanced_networkimage: ^0.4.15
  random_color: ^1.0.3
  of_cache: ^0.0.1

  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.4.0
  mobx_codegen: ^0.1.2


flutter:


  uses-material-design: true

  assets:
    - assets/flare/
    - assets/img/
    - assets/nima/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
